version = "1.0"

artifacts = ["/app"]

[metadata]
category = "parsers-and-languages"
programming_language = "C"

[verifier]
environment_mode = "separate"
network_mode = "no-network"
timeout_sec = 1800.0
test_case_count = 39

[agent]
timeout_sec = 14400.0

[environment]
docker_image = "ghcr.io/facebookresearch/e2e-swe:packcc"
cpus = 6
memory_mb = 8192
storage_mb = 51200
allow_internet = false
