import com.squareup.javapoet.*;
import javax.lang.model.element.Modifier;
import java.util.*;
import java.util.function.Supplier;

/** Capability group: JavaFile emission — package declaration, import collection + sorting,
 *  simple-name vs fully-qualified emission on collision, java.lang handling, static imports,
 *  skipJavaLangImports, default (empty) package, file comment, custom indent. */
public class JavaFileHarness {
    static String norm(String s) { return s.replace("\n", "\\n"); }

    static String file(String pkg, TypeSpec t) {
        return norm(JavaFile.builder(pkg, t).build().toString());
    }

    public static void main(String[] args) throws Exception {
        LinkedHashMap<String, Supplier<String>> c = new LinkedHashMap<>();

        c.put("jf_basic_import", () ->
            file("com.example", TypeSpec.classBuilder("Foo")
                .addField(ClassName.get("java.util", "Date"), "date", Modifier.PRIVATE)
                .build()));
        c.put("jf_two_imports_sorted", () ->
            file("com.example", TypeSpec.classBuilder("Foo")
                .addField(ClassName.get("java.util", "Map"), "m", Modifier.PRIVATE)
                .addField(ClassName.get("java.io", "File"), "f", Modifier.PRIVATE)
                .build()));
        c.put("jf_collision_fqn", () ->
            file("com.example", TypeSpec.classBuilder("Foo")
                .addField(ClassName.get("java.util", "Date"), "utilDate", Modifier.PRIVATE)
                .addField(ClassName.get("java.sql", "Date"), "sqlDate", Modifier.PRIVATE)
                .build()));
        c.put("jf_javalang_default", () ->
            file("com.example", TypeSpec.classBuilder("Foo")
                .addField(ClassName.get("java.lang", "String"), "s", Modifier.PRIVATE)
                .build()));
        c.put("jf_skip_javalang", () ->
            norm(JavaFile.builder("com.example", TypeSpec.classBuilder("Foo")
                .addField(ClassName.get("java.lang", "String"), "s", Modifier.PRIVATE)
                .build()).skipJavaLangImports(true).build().toString()));
        c.put("jf_same_package_no_import", () ->
            file("com.example", TypeSpec.classBuilder("Foo")
                .addField(ClassName.get("com.example", "Bar"), "bar", Modifier.PRIVATE)
                .build()));
        c.put("jf_static_import", () ->
            norm(JavaFile.builder("com.example", TypeSpec.classBuilder("Foo")
                .addMethod(MethodSpec.methodBuilder("empty")
                    .returns(ParameterizedTypeName.get(ClassName.get(List.class), ClassName.get(String.class)))
                    .addStatement("return $T.emptyList()", ClassName.get("java.util", "Collections"))
                    .build())
                .build())
                .addStaticImport(ClassName.get("java.util", "Collections"), "emptyList")
                .build().toString()));
        c.put("jf_default_package", () ->
            file("", TypeSpec.classBuilder("Foo")
                .addField(ClassName.get("java.util", "Date"), "date", Modifier.PRIVATE)
                .build()));
        c.put("jf_file_comment", () ->
            norm(JavaFile.builder("com.example", TypeSpec.classBuilder("Foo").build())
                .addFileComment("Generated by $L. Do not edit.", "JavaPoet")
                .build().toString()));
        c.put("jf_custom_indent", () ->
            norm(JavaFile.builder("com.example", TypeSpec.classBuilder("Foo")
                .addMethod(MethodSpec.methodBuilder("noop").build())
                .build())
                .indent("    ")
                .build().toString()));

        Runner.run(c, args);
    }
}
