// Shared offline test runner for the `stylesheet-tree` task. Emits a CTRF report directly to
// /logs/verifier/ctrf.json — no third-party test framework is vendored, because the library under
// test is native ESM and runs on the image's Node 20 as-is.
//
// Design (mirrors the gold multilingual pattern's Runner + oracle):
//   * Each capability driver file (`*.harness.mjs`) default-exports an array of cases:
//         export default [ { name: 'unique case name', run: async () => { /* assert; throw on fail */ } }, ... ]
//     One case = one CTRF entry. A case passes iff `run()` returns without throwing.
//   * `manifest.json` (committed, generated by `--capture` against ground truth) is the CANONICAL
//     list of every case name, grouped by driver. It is the fixed denominator: if a driver fails to
//     import (agent library throws at load) or a case name is missing, every case the manifest
//     attributes to it is recorded FAILED. So a broken submission scores 0 rather than crashing the
//     grader, and the denominator never drifts.
//   * PROCESS ISOLATION: in grade mode the parent spawns ONE CHILD PROCESS PER DRIVER
//     (`--grade-driver <file>`), each with a hard wall-clock timeout and a bounded V8 heap
//     (--max-old-space-size). A pathological agent implementation that infinite-loops-with-
//     allocation (OOM, exit 134), hard-crashes, or hangs therefore fails ONLY that driver's cases —
//     it can no longer zero the whole suite by killing a single shared process. Within a child, each
//     case additionally has a per-case async wall-clock timeout. The denominator stays fixed at the
//     manifest count in every failure mode.
//
// Modes:
//   node run.mjs --capture              Import every driver, collect case names, write manifest.json.
//                                       Also runs each case and FAILS (non-zero exit) if any throws —
//                                       so --capture doubles as a GT self-check.
//   node run.mjs                        Grade: spawn one child per driver, aggregate, write CTRF.
//                                       Never throws.
//   node run.mjs --grade-driver <file>  Internal: run one driver's cases, print JSONL to stdout.

import { readdir, mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';
import { spawn } from 'node:child_process';

const TESTS_DIR = dirname(fileURLToPath(import.meta.url));
const MANIFEST_PATH = join(TESTS_DIR, 'manifest.json');
const CTRF_DIR = process.env.CTRF_DIR || '/logs/verifier';
const CTRF_PATH = join(CTRF_DIR, 'ctrf.json');
const PER_CASE_TIMEOUT_MS = Number(process.env.PER_CASE_TIMEOUT_MS || 20000);
// Whole-driver wall-clock cap (parent-enforced kill) and per-child heap cap. A driver with a few
// cases needs little time; a runaway case is killed well within the verifier's timeout_sec.
const PER_DRIVER_TIMEOUT_MS = Number(process.env.PER_DRIVER_TIMEOUT_MS || 120000);
const CHILD_HEAP_MB = Number(process.env.CHILD_HEAP_MB || 1024);

const DRIVER_SUFFIX = '.harness.mjs';

async function listDriverFiles() {
    const entries = await readdir(TESTS_DIR);
    return entries.filter((f) => f.endsWith(DRIVER_SUFFIX)).sort();
}

// Import a driver module and return its case array, or an error string if the module fails to load.
async function loadDriver(file) {
    try {
        const mod = await import(pathToFileURL(join(TESTS_DIR, file)).href);
        const cases = mod.default;
        if (!Array.isArray(cases)) {
            return { error: `driver ${file} did not default-export an array of cases` };
        }
        return { cases };
    } catch (e) {
        return { error: `import of ${file} failed: ${e && e.stack ? e.stack : e}` };
    }
}

function withTimeout(fn, ms) {
    return new Promise((resolve, reject) => {
        let done = false;
        const timer = setTimeout(() => {
            if (!done) {
                done = true;
                reject(new Error(`case exceeded per-case timeout of ${ms} ms`));
            }
        }, ms);
        Promise.resolve()
            .then(fn)
            .then(
                (v) => { if (!done) { done = true; clearTimeout(timer); resolve(v); } },
                (e) => { if (!done) { done = true; clearTimeout(timer); reject(e); } },
            );
    });
}

// ---- capture mode: build the oracle manifest against ground truth ----
async function runCapture() {
    const files = await listDriverFiles();
    const manifest = [];
    let failures = 0;

    for (const file of files) {
        const loaded = await loadDriver(file);
        if (loaded.error) {
            console.error(`CAPTURE ERROR: ${loaded.error}`);
            failures++;
            continue;
        }
        const names = [];
        for (const c of loaded.cases) {
            if (!c || typeof c.name !== 'string' || typeof c.run !== 'function') {
                console.error(`CAPTURE ERROR: ${file} has a malformed case: ${JSON.stringify(c)}`);
                failures++;
                continue;
            }
            names.push(c.name);
            try {
                await withTimeout(c.run, PER_CASE_TIMEOUT_MS);
            } catch (e) {
                console.error(`CAPTURE FAIL [${file}] ${c.name}: ${e && e.message ? e.message : e}`);
                failures++;
            }
        }
        manifest.push({ file, cases: names });
    }

    const seen = new Set();
    for (const d of manifest) {
        for (const n of d.cases) {
            if (seen.has(n)) {
                console.error(`CAPTURE ERROR: duplicate case name across suite: ${n}`);
                failures++;
            }
            seen.add(n);
        }
    }

    await writeFile(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + '\n');
    const total = manifest.reduce((a, d) => a + d.cases.length, 0);
    console.log(`captured ${total} cases across ${manifest.length} drivers -> ${MANIFEST_PATH}`);
    if (failures > 0) {
        console.error(`CAPTURE had ${failures} failure(s) — ground truth is not clean.`);
        process.exit(1);
    }
    console.log('CAPTURE clean: every case passed against ground truth.');
}

// ---- child mode: run one driver's cases, emit one JSON line per case to stdout ----
async function gradeOneDriver(file) {
    const loaded = await loadDriver(file);
    const byName = new Map();
    if (loaded.cases) {
        for (const c of loaded.cases) {
            if (c && typeof c.name === 'string' && typeof c.run === 'function') {
                byName.set(c.name, c);
            }
        }
    }
    // Run in the driver's own declared order; the parent reconciles against the manifest.
    const order = loaded.cases ? loaded.cases.map((c) => c && c.name).filter(Boolean) : [];
    for (const name of order) {
        const t0 = Date.now();
        if (loaded.error) {
            emit({ name, status: 'failed', duration: 0, message: loaded.error.slice(0, 2000) });
            continue;
        }
        const c = byName.get(name);
        try {
            await withTimeout(c.run, PER_CASE_TIMEOUT_MS);
            emit({ name, status: 'passed', duration: Date.now() - t0 });
        } catch (e) {
            const msg = e && e.stack ? e.stack : (e && e.message ? e.message : String(e));
            emit({ name, status: 'failed', duration: Date.now() - t0, message: String(msg).slice(0, 2000) });
        }
    }
    // If the module itself failed to import, emit nothing for its (unknown) cases; the parent marks
    // every manifest case for this driver as failed. Report the import error once for the log.
    if (loaded.error) {
        process.stderr.write(loaded.error.slice(0, 2000) + '\n');
    }
}

function emit(obj) {
    process.stdout.write('CASE ' + JSON.stringify(obj) + '\n');
}

// Spawn a child to grade one driver; return a Map(name -> result) of what it reported.
function spawnDriver(file) {
    return new Promise((resolve) => {
        const results = new Map();
        let stderr = '';
        let buf = '';
        const child = spawn(
            process.execPath,
            [`--max-old-space-size=${CHILD_HEAP_MB}`, fileURLToPath(import.meta.url), '--grade-driver', file],
            { cwd: TESTS_DIR, env: process.env, stdio: ['ignore', 'pipe', 'pipe'] },
        );
        const killTimer = setTimeout(() => { try { child.kill('SIGKILL'); } catch { /* */ } }, PER_DRIVER_TIMEOUT_MS);

        child.stdout.on('data', (d) => {
            buf += d.toString();
            let nl;
            while ((nl = buf.indexOf('\n')) >= 0) {
                const line = buf.slice(0, nl);
                buf = buf.slice(nl + 1);
                if (line.startsWith('CASE ')) {
                    try {
                        const r = JSON.parse(line.slice(5));
                        if (r && typeof r.name === 'string') { results.set(r.name, r); }
                    } catch { /* ignore malformed line */ }
                }
            }
        });
        child.stderr.on('data', (d) => { stderr += d.toString(); });
        child.on('close', (code, signal) => {
            clearTimeout(killTimer);
            resolve({ results, code, signal, stderr });
        });
        child.on('error', (err) => {
            clearTimeout(killTimer);
            resolve({ results, code: -1, signal: null, stderr: String(err) });
        });
    });
}

// ---- parent grade mode: one child per driver, aggregate against the manifest ----
async function runGrade() {
    await mkdir(CTRF_DIR, { recursive: true });

    if (!existsSync(MANIFEST_PATH)) {
        await writeZeroCtrf('no manifest');
        console.error(`no manifest at ${MANIFEST_PATH}; wrote zero-result CTRF`);
        return;
    }

    const manifest = JSON.parse(await readFile(MANIFEST_PATH, 'utf8'));
    const tests = [];
    const start = Date.now();

    for (const driver of manifest) {
        const { results, code, signal, stderr } = await spawnDriver(driver.file);
        // Reason a case is failed when the child produced no result for it (crash / OOM / kill / hang).
        const crashNote = signal
            ? `driver process killed (signal ${signal}) — likely OOM/timeout in the agent implementation`
            : code !== 0
                ? `driver process exited with code ${code}${stderr ? ': ' + stderr.slice(0, 500) : ''}`
                : 'case not reported by driver (library incomplete?)';
        for (const name of driver.cases) {
            const r = results.get(name);
            if (r && (r.status === 'passed' || r.status === 'failed')) {
                tests.push({ name, status: r.status, duration: r.duration || 0, ...(r.message ? { message: r.message } : {}) });
            } else {
                tests.push({ name, status: 'failed', duration: 0, message: crashNote.slice(0, 2000) });
            }
        }
    }

    const stop = Date.now();
    const passed = tests.filter((t) => t.status === 'passed').length;
    const failed = tests.filter((t) => t.status === 'failed').length;
    const report = {
        results: {
            tool: { name: 'stylesheet-tree-runner' },
            summary: { tests: tests.length, passed, failed, pending: 0, skipped: 0, other: 0, start, stop },
            tests,
        },
    };
    await writeFile(CTRF_PATH, JSON.stringify(report));
    console.log(`graded ${tests.length} cases: ${passed} passed, ${failed} failed -> ${CTRF_PATH}`);
}

async function writeZeroCtrf(reason) {
    const now = Date.now();
    await writeFile(CTRF_PATH, JSON.stringify({
        results: {
            tool: { name: 'stylesheet-tree-runner', reason },
            summary: { tests: 0, passed: 0, failed: 0, pending: 0, skipped: 0, other: 0, start: now, stop: now },
            tests: [],
        },
    }));
}

const mode = process.argv[2];
try {
    if (mode === '--capture') {
        await runCapture();
    } else if (mode === '--grade-driver') {
        await gradeOneDriver(process.argv[3]);
    } else {
        await runGrade();
    }
} catch (e) {
    console.error(`runner crashed: ${e && e.stack ? e.stack : e}`);
    if (mode !== '--capture' && mode !== '--grade-driver') {
        try {
            await mkdir(CTRF_DIR, { recursive: true });
            await writeZeroCtrf('runner crashed');
        } catch { /* ignore */ }
    }
    process.exit(mode === '--capture' ? 1 : 0);
}
